version: '3.9'

services:
  backend:
    build:
      context: ../src/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/task-management
      - JWT_SECRET=development_secret
      - JWT_EXPIRATION=1d
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ../src/backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network
    command: npm run dev

  frontend:
    build:
      context: ../src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:5000
    volumes:
      - ../src/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: 